FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as BUILD
COPY . /WebApplication
WORKDIR /WebApplication
RUN dotnet publish -c Release -o ../publish

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 as RELEASE
COPY --from=BUILD ./publish /app
WORKDIR /app
ENTRYPOINT [ "dotnet", "WebApplication.dll" ]

# docker build . -t k8s4devs.azurecr.io/k8s4devs/webapp:v0.2
# docker build . -t tcdoan/webapp:v1
# docker push tcdoan/webapp:v1
# docker push k8s4devs.azurecr.io/k8s4devs/webapp:v0.2
# kubectl create secret docker-registry tcdoan --docker-username=tcdoan --docker-password=Password  --docker-email=tcdoan@gmail.com
